### PR TITLE
[wip] Jenkins

### PR DESCRIPTION
**Pull request by ralphtheninja**
An empty `Jenkinsfile` so we have something to work with.

All builds will show up here https://ci.delta.chat/blue/organizations/jenkins/deltachat-android-ii/activity

The docker image in a separate PR: https://github.com/deltachat/docker-images/pull/1

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Building locally and it looks like:

screenshot from 2018-11-26 20-49-44

The `:lint` step seems to take forever. Is this normal to take up to one hour?

**Comment by ralphtheninja** [comment]
Eventually the `:lint` step crashes with:

screenshot from 2018-11-26 21-52-14

But after that the build reports that the build was successful 

screenshot from 2018-11-26 21-55-01

Maybe we can just skip the `:lint` step somehow?

**Comment by angelo-fuchs** [comment]
@ralphtheninja Did you choose to abandon this or is it done somewhere else?

**Comment by ralphtheninja** [comment]
I abandoned it.

**Pull request closed without merging**
