### PR TITLE
[WIP] If contacts are already selected, resort them to the top of the list.

### LINKED ISSUE #226: collect selected contacts at the top on group creation
when creating a group, in a long list of contacts, it's difficult to keep the overview about who is selected... how about collecting the checked contacts at the top? or at least show a counter about how many contacts are selected...?
telegram UI also listed them at the top and said "5 members and me" in the title

### PR DESCRIPTION
**Pull request by chklump**
This should fix #226.
I still need to sort some bugs out, but last issue, I was on, was suddenly fixed by someone else. That's why I'm already creating this pull request.

### CODE REVIEW

**Comment by r10s** [comment]
hi @chklump, thanks for pushing this forward.

however, i am not sure, if resorting the list during using it is the best approach.

as you mentioned, its a big buggy, esp. wrt the "new contact" field that is not available after the first selection and also sometimes the first entry is selected no matter what is entered.

of couse, this all can be fixed, but here are also some ux-issues as a more complicated ordering of the list - "A", "B", "C" and potentially all letters are shown twice, and it is harder to change a selecion image sth. as name@work.org and name@home.org where one is selected and the other is not - these would show up at different positions in the list.

so, i am not sure it is worth following this way.

i would prefer having an additional, small control at the top of the list showing the selected items, either as text or maybe the avatars in a row or so (the latter is done by whats app).

however, for now i would also be fine to leave it "as is" (this is done by signal) - i think #266 at least partly refers to the things you've already fixed in 

finally, i want to mention that the "add members" activity is not really meant to be the overview of the selected members - this is already done by the "create|edit group" activity. 

maybe it is also helpful to make this activity more attractive first, eg. showing the avatars and using the same items (see #162) - might be that at the end this is totally sufficient :)

what do you think?

**Comment by r10s** [comment]
> I think that, too. But then there shouldn't be the possibility to remove members from the group by deselecting it from there (although it was me implementing it)

why not?

i would regard the new-group-activity as an overview where the selected members are shown and activities can be started to modify the member list - either by the select-member-activity or by qr-code-scanning.

> Members already in the group should simply not be included in the "add members" list, since you can't still add them to the list.

i would leave them there as selected. the number of selected members are small and esp. for simiar email-addresses it is a good information that sth. is selected.

in general, i would like to see the entry field below the title so that the title can show number of items. and the entry field could show the selected members as "chips" then - this would not consume much space on the screen and is rather clear imho.

this would also be rather independent from other decisions.

however, i think also the current state is not _that_ bad, so i would also be fine with leaving the group-activities alone _for now_ and thinking this over in some weeks or so. and go to other issues first - there is no lack of them, fortunately :)

**Comment by chklump** [comment]
>>    I think that, too. But then there shouldn't be the possibility to remove members from the group by deselecting it from there (although it was me implementing it)

> why not?

Because it seems somehow wrong to me to click on "add member" and then doing the opposite action. Then it should be some kind of "manage group members" (lacking a better word). But then, you should also not be able to delete members from the "new-group-activity", so that you can't do the same thing in different places. Or is it okay? I'm not to sure thinking about that now.

> in general, i would like to see the entry field below the title so that the title can show number of items.

Just for me to understand: There is no title at the moment, or is there?

And yes, your right, it's probably splitting hairs.
I will go for some more urgent issue. Can I assign myself somehow to them?

**Comment by r10s** [comment]
> Can I assign myself somehow to them?

does "assign yourseff" work for you? otherwise please contact me at r10s at b44t dot com :)

**Pull request closed without merging**
